title: "Michael Smith"
description: >
  Portfolio showcasing deep expertise in networking, cloud architecture, and AI/ML development, built across a career of delivering advanced technical solutions and leading modernization initiatives.
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Optional settings
logo: /images/profile.jpg
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/michaeljsmith35/
  - name: Email
    url: mailto:1973.mjsmith@gmail.com

defaults:
  - scope:
      path: ""
    values:
      head: head-custom.html
